name: helio

services:
  nginx:
    image: nginx:alpine
    platform: linux/x86_64
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../laravel:/var/www/html
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - laravel-network

  laravel:
    working_dir: /var/www/html
    build:
      args:
        USER: www-data
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../laravel:/var/www/html
    networks:
      - laravel-network

  reverb:
    build:
      args:
        USER: www-data
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    ports:
      - "8080:8080"
    environment:
      - REVERB_SERVER_HOST=0.0.0.0
      - REVERB_SERVER_PORT=8080
    volumes:
      - ../laravel:/var/www/html
    depends_on:
      - redis
      - database
    networks:
      - laravel-network

  database:
    image: mysql:latest
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel-network

  maildev:
    image: maildev/maildev
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - laravel-network

  redis:
    image: redis:latest
    environment:
      - REDIS_CLIENT=phpredis
    volumes:
      - ./redisdata:/data
    networks:
      - laravel-network

  queue:
    build:
      args:
        USER: www-data
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    command: php artisan queue:work
    volumes:
      - ../laravel:/var/www/html
    depends_on:
      - redis
      - database
    networks:
      - laravel-network

  scheduler:
    build:
      args:
        USER: www-data
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    command: sh -c "while [ true ]; do php artisan schedule:run --no-interaction; sleep 60; done"
    volumes:
      - ../laravel:/var/www/html
    depends_on:
      - redis
      - database
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
